GET http://localhost:3001/students

###

GET http://localhost:3001/students/1

###

POST http://localhost:3001/auth/login
content-type: application/json

{ 
    "table": "students",
    "email": "lacitis18@inbox.lv", 
    "password": "parole" 
}